---
swagger: '2.0'
info:
  title: Customer API v1
  description: Customer relationship API
  version: 0.1.0
  host: localhost:8762/api-customer
paths:
  /customer:
    get:
      tags:
        - customer
      summary: Find all customers
      description: Returns list of customers
      operationId: customers
      produces:
        - application/json
      responses:
        '200':
          description: Customers found
          schema:
            type: array
            items:
              "$ref": "#/definitions/Customer"
        '404':
          description: No customer found
  /customer/{customerId}:
    get:
      tags:
        - customer
      summary: Find customer by ID
      description: Returns a single customer
      operationId: customerById
      produces:
        - application/json
      parameters:
        - name: customerId
          in: path
          description: ID of customer to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Customer found
          schema:
            "$ref": "#/definitions/Customer"
        '400':
          description: Invalid ID supplied
        '404':
          description: Customer not found
definitions:
  Customer:
    type: object
    properties:
      customerId:
        type: integer
        format: int64
      name:
        type: string
      surname:
        type: string
      email:
        type: string
      phone:
        type: string
      dateBirth:
        type: string
        format: date