---
swagger: '2.0'
info:
  title: Notification API
  description: Notification API
  version: 0.1.0
  host: localhost:8762/api-notification
paths:
  /notification:
    post:
      tags:
        - notification
      summary: Emits a notification
      description: Emits a notification
      operationId: postNotification
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: document
          description: The document to create.
          schema:
            $ref: '#/definitions/Notification'
      responses:
        '201':
          description: Created
          schema:
            "$ref": "#/definitions/Notification"
definitions:
  Notification:
    type: object
    properties:
      notificationId:
        type: string
        readOnly: true
      type:
        type: string
        enum: [SMS, EMAIL]
      creationDate:
        type: string
        format: date
      source:
        type: string
      label:
        type: string
      message:
        type: string
        