@startuml
[-> "Contract API": POST /contract
note left of "Contract API"
{
    "customerId": 1,
    "creationDate": "2020-01-01",
    ...
}
end note
activate "Contract API"
"Contract API" -> "Customer API": GET /customer/{customerId}
activate "Customer API"
"Customer API" --> "Contract API": 200 OK
note left of "Customer API"
 {
     "customerId": 1,
     "name": "Bob",
     ...
 }
end note
|||
|||
deactivate "Customer API"
"Contract API" -> "Contract API": Database transaction
[<-- "Contract API": 201 Created
deactivate "Contract API"
@enduml