spring:
  application:
    name: api-contract
  datasource:
    url: jdbc:h2:mem:customers;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
    name: contracts
    platform: h2
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    
document-service:
  routing-key:
    contract: contractRoutingKey
    document: documentRoutingKey

feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
