spring:
  application:
    name: api-customer
  cloud:
    config:
      uri: http://${eureka.instance.hostname}:8888

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: api-customer
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
