server:
  port: 26379

spring:
  application:
    name: eureka-sidecar-redis
  cloud:
    config:
      uri: http://${eureka.instance.hostname}:8888
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true

sidecar:
  hostname: ${eureka.instance.hostname}
  port: 6379
  timeout:
    socket: 2000
    shutdown: 2000
    command: 1500
  health-uri: http://${eureka.instance.hostname}:${server.port}/redis/health
  home-page-uri: ${eureka.instance.hostname}:${server.port}/
